### PR TITLE
OS-Specific install instructions

### PR DESCRIPTION
**Pull request by rex**
Because the installer is Mac OS X-specific, I felt compelled to update the readme to accommodate non-Mac users in the installation instructions. 

Additionally, I updated the Mac installation to retrieve the script via `curl` and pipe it straight to `bash`. No need to download it before running it! :)

### CODE REVIEW

**Comment by rex** [comment]
Damn conflicts. Let me fix them and push the fixes.

**Comment by NoahBuscher** [comment]
Ah! Sorry. Thanks!

**Comment by rex** [comment]
It's all good! I just resolved the conflicts and the updates eagerly await your approval :D

**Comment by NoahBuscher** [comment]
Looks great! Thanks a ton! :100:

**Comment by rex** [comment]
Not a problem sir! Least I could do to repay you for the awesome theme!

**Comment by NoahBuscher** [comment]
Haha! Thanks. It was in need of some :heart: and I'm happy that we have it back to working order now.

**Pull request merged**
